name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: |
        cd frontend && pnpm install
        cd ../backend && pnpm install
    
    - name: Run frontend tests
      run: cd frontend && pnpm test
    
    - name: Run backend tests
      run: cd backend && pnpm test

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    
    - name: Install pnpm
      run: npm install -g pnpm
    
    - name: Install dependencies
      run: |
        cd frontend && pnpm install
        cd ../backend && pnpm install
    
    - name: Lint frontend
      run: cd frontend && pnpm run lint
    
    - name: Lint backend
      run: cd backend && pnpm run lint
